// <auto-generated />
using Kast.Models.Dnd5E;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Kast.Migrations
{
    [DbContext(typeof(Dnd5EContext))]
    partial class Dnd5EContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kast.Models.Dnd5E.Spell", b =>
                {
                    b.Property<int>("SpellId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CastingTime");

                    b.Property<string>("Components");

                    b.Property<string>("Damage");

                    b.Property<string>("DamageType");

                    b.Property<string>("Description");

                    b.Property<string>("Duration");

                    b.Property<int>("Level");

                    b.Property<string>("Name");

                    b.Property<string>("Range");

                    b.Property<bool>("Retual");

                    b.Property<string>("Schole");

                    b.HasKey("SpellId");

                    b.ToTable("Spells");
                });
#pragma warning restore 612, 618
        }
    }
}
