// <auto-generated />
using Kast.Roleplaying.Models.Dnd5Edition;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Kast.Roleplaying.Migrations
{
    [DbContext(typeof(Dnd5EContext))]
    [Migration("20180402065205_InitialSpellbook")]
    partial class InitialSpellbook
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kast.Roleplaying.Models.Dnd5Edition.Spell", b =>
                {
                    b.Property<int>("SpellId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CastingTime");

                    b.Property<string>("ClassesCanCast");

                    b.Property<string>("Components");

                    b.Property<bool>("Concentration");

                    b.Property<string>("Damage");

                    b.Property<string>("DamageType");

                    b.Property<string>("Description");

                    b.Property<string>("Duration");

                    b.Property<string>("InClass");

                    b.Property<int>("Level");

                    b.Property<string>("Material");

                    b.Property<string>("Name");

                    b.Property<string>("Range");

                    b.Property<bool>("Retual");

                    b.Property<string>("Schole");

                    b.Property<int>("SpellBookId");

                    b.HasKey("SpellId");

                    b.HasIndex("SpellBookId");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("Kast.Roleplaying.Models.Dnd5Edition.SpellBook", b =>
                {
                    b.Property<int>("SpellBookId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.HasKey("SpellBookId");

                    b.ToTable("SpellBooks");
                });

            modelBuilder.Entity("Kast.Roleplaying.Models.Dnd5Edition.Spell", b =>
                {
                    b.HasOne("Kast.Roleplaying.Models.Dnd5Edition.SpellBook")
                        .WithMany("Spells")
                        .HasForeignKey("SpellBookId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
